<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="selenium.base" href="https://www.yyddd.com/" />
<title>11</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">11</td></tr>
</thead><tbody>
<tr>
	<td>type</td>
	<td>xpath=(//input[@data-this=&quot;goodsdiscprice&quot;])</td>
	<td></td>
</tr>
<tr>
	<td>sendKeys</td>
	<td>xpath=(//input[@data-this=&quot;goodsdiscprice&quot;])</td>
	<td>20</td>
</tr>
<tr>
	<td>type</td>
	<td>xpath=(//input[@data-this=&quot;goodsdiscprice&quot;])</td>
	<td></td>
</tr>
<tr>
	<td>sendKeys</td>
	<td>xpath=(//input[@data-this=&quot;goodsdiscprice&quot;])</td>
	<td>80</td>
</tr>
<!--库存-->
<tr>
	<td>storeText</td>
	<td>//span[@class=&quot;font-size-16 red-600 start&quot;]</td>
	<td>a</td>
</tr>
<tr>
	<td>storeText</td>
	<td>//span[@class=&quot;font-size-16 red-600 end&quot;]</td>
	<td>s</td>
</tr>
<tr>
	<td>storeText</td>
	<td>//span[@class=&quot;font-size-16 red-600 goodsin&quot;]</td>
	<td>d</td>
</tr>
<tr>
	<td>storeText</td>
	<td>//span[@class=&quot;font-size-16 red-600 goodsout&quot;]</td>
	<td>f</td>
</tr>
<tr>
	<td>storeText</td>
	<td>//span[@class=&quot;font-size-16 red-600 start&quot;]</td>
	<td>g</td>
</tr>
<tr>
	<td>storeText</td>
	<td>//span[@class=&quot;font-size-16 red-600 end&quot;]</td>
	<td>h</td>
</tr>
<tr>
	<td>storeText</td>
	<td>//span[@class=&quot;font-size-16 red-600 goodsin&quot;]</td>
	<td>j</td>
</tr>
<tr>
	<td>storeText</td>
	<td>//span[@class=&quot;font-size-16 red-600 goodsout&quot;]</td>
	<td>k</td>
</tr>
<!--进货-->
<tr>
	<td>storeText</td>
	<td>id=sellmoney</td>
	<td>z</td>
</tr>
<tr>
	<td>storeText</td>
	<td>id=sellnum</td>
	<td>x</td>
</tr>
<tr>
	<td>storeText</td>
	<td>id=selldisc</td>
	<td>c</td>
</tr>
<!--销售-->
<tr>
	<td>storeText</td>
	<td>id=sellmoney</td>
	<td>q</td>
</tr>
<tr>
	<td>storeText</td>
	<td>id=sellnum</td>
	<td>w</td>
</tr>
<tr>
	<td>storeText</td>
	<td>id=selldisc</td>
	<td>e</td>
</tr>
<tr>
	<td>storeText</td>
	<td>//h5[@class=&quot;green-600 margin-0 sellmoney&quot;]</td>
	<td>r</td>
</tr>
<tr>
	<td>storeText</td>
	<td>//h5[@class=&quot;red-600 margin-0 outAmount&quot;]</td>
	<td>t</td>
</tr>
<tr>
	<td>storeText</td>
	<td>//h5[@class=&quot;green-600 margin-0 profit&quot;]</td>
	<td>y</td>
</tr>
<tr>
	<td></td>
	<td></td>
	<td></td>
</tr>
<!--获取报表数据-->
<tr>
	<td>click</td>
	<td>link=工作</td>
	<td></td>
</tr>
<tr>
	<td>waitForText</td>
	<td>xpath=//div[@data-power=&quot;310|320|330|340|350|360|370&quot;]</td>
	<td>报表</td>
</tr>
<tr>
	<td>click</td>
	<td>xpath=//div[@data-power=&quot;310|320|330|340|350|360|370&quot;]</td>
	<td></td>
</tr>
<tr>
	<td>waitForText</td>
	<td>xpath=//li[@data-power=&quot;330&quot;]/div/div/h4</td>
	<td>进货报表</td>
</tr>
<tr>
	<td>click</td>
	<td>xpath=//li[@data-power=&quot;330&quot;]</td>
	<td></td>
</tr>
<tr>
	<td>pause</td>
	<td>500</td>
	<td></td>
</tr>
<tr>
	<td>waitForText</td>
	<td>//ul/li/h5</td>
	<td>按商品分析</td>
</tr>
<tr>
	<td>pause</td>
	<td>500</td>
	<td></td>
</tr>
<tr>
	<td>storeText</td>
	<td>id=sellmoney</td>
	<td>z</td>
</tr>
<tr>
	<td>store</td>
	<td>javascript{lz(storedVars.f)+860}</td>
	<td>f1</td>
</tr>
<tr>
	<td>storeText</td>
	<td>id=sellnum</td>
	<td>x</td>
</tr>
<tr>
	<td>store</td>
	<td>javascript{lz(storedVars.f)+860}</td>
	<td>f1</td>
</tr>
<tr>
	<td>storeText</td>
	<td>id=selldisc</td>
	<td>c</td>
</tr>
<tr>
	<td>store</td>
	<td>javascript{lz(storedVars.f)+860}</td>
	<td>f1</td>
</tr>
<tr>
	<td></td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>goBack</td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>waitForText</td>
	<td>//li[@data-power=&quot;340&quot;]/div/div/h4</td>
	<td>库存报表</td>
</tr>
<tr>
	<td>click</td>
	<td>//li[@data-power=&quot;340&quot;]</td>
	<td></td>
</tr>
<tr>
	<td>pause</td>
	<td>500</td>
	<td></td>
</tr>
<tr>
	<td>waitForText</td>
	<td>css=li.list-group-item &gt; h5</td>
	<td>按商品分析</td>
</tr>
<tr>
	<td></td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td></td>
	<td></td>
	<td></td>
</tr>
</tbody></table>
</body>
</html>
