from selenium import webdriver
from time import sleep
import unittest,sys,os
sys.path.append("./page")
from page.page_daoru import login

class loginTest(unittest.TestCase):
	'''批量导入功能测试'''

	def setUp(self):
		self.driver = webdriver.Chrome()

	def test_1kehu(self):
		#导入正确
		login(self.driver).user_login()
		login(self.driver).clickqingkong()
		sleep(1)
		login(self.driver).clickkehu()
		login(self.driver).clickX()
		login(self.driver).clickdaoru()
		sleep(1)
		login(self.driver).clickshang()
		sleep(1)
		os.system("C:\\Users\\Administrator\\MyScript\\excel\\lq.exe")
		sleep(2)
		login(self.driver).clicktijiao()
		sleep(3)
		self.assertEqual(login(self.driver).clickwanbi(),'导入完毕')
		sleep(1)
		login(self.driver).clickque()
		sleep(5)
		self.assertEqual(login(self.driver).dui(),'20')
		self.assertEqual(login(self.driver).cuo(),'0')
		#导入错误
		sleep(1)
		login(self.driver).clickshang2()
		sleep(1)
		os.system("C:\\Users\\Administrator\\MyScript\\excel\\le.exe")
		sleep(2)
		login(self.driver).clicktijiao()
		sleep(3)
		self.assertEqual(login(self.driver).clickwanbi(),'导入完毕')
		sleep(1)
		login(self.driver).clickque()
		sleep(5)
		self.assertEqual(login(self.driver).dui(),'10')
		self.assertEqual(login(self.driver).cuo(),'10')
		#导入大量
		sleep(1)
		login(self.driver).clickshang2()
		sleep(1)
		os.system("C:\\Users\\Administrator\\MyScript\\excel\\lw.exe")
		sleep(2)
		login(self.driver).clicktijiao()
		sleep(20)
		self.assertEqual(login(self.driver).clickwanbi(),'导入完毕')
		sleep(1)
		login(self.driver).clickque()
		sleep(5)
		self.assertEqual(login(self.driver).dui(),'1774')
		self.assertEqual(login(self.driver).cuo(),'0')
		sleep(1)

	def test_2gonghuoshang(self):
		#导入正确
		login(self.driver).user_login()
		sleep(1)
		login(self.driver).clickghs()
		login(self.driver).clickX()
		login(self.driver).clickdaoru2()
		sleep(1)
		login(self.driver).clickshang()
		sleep(1)
		os.system("C:\\Users\\Administrator\\MyScript\\excel\\lq.exe")
		sleep(2)
		login(self.driver).clicktijiao()
		sleep(3)
		self.assertEqual(login(self.driver).clickwanbi(),'导入完毕')
		sleep(1)
		login(self.driver).clickque()
		sleep(5)
		self.assertEqual(login(self.driver).dui(),'20')
		self.assertEqual(login(self.driver).cuo(),'0')
		#导入错误
		sleep(1)
		login(self.driver).clickshang2()
		sleep(1)
		os.system("C:\\Users\\Administrator\\MyScript\\excel\\le.exe")
		sleep(2)
		login(self.driver).clicktijiao()
		sleep(3)
		self.assertEqual(login(self.driver).clickwanbi(),'导入完毕')
		sleep(1)
		login(self.driver).clickque()
		sleep(5)
		self.assertEqual(login(self.driver).dui(),'10')
		self.assertEqual(login(self.driver).cuo(),'10')
		#导入大量
		sleep(1)
		login(self.driver).clickshang2()
		sleep(1)
		os.system("C:\\Users\\Administrator\\MyScript\\excel\\lw.exe")
		sleep(2)
		login(self.driver).clicktijiao()
		sleep(20)
		self.assertEqual(login(self.driver).clickwanbi(),'导入完毕')
		sleep(1)
		login(self.driver).clickque()
		sleep(5)
		self.assertEqual(login(self.driver).dui(),'1774')
		self.assertEqual(login(self.driver).cuo(),'0')
		sleep(1)

	def test_3shangpin(self):
		# 导入正确
		login(self.driver).user_login()
		sleep(2)
		login(self.driver).clicksp()
		login(self.driver).clickX()
		sleep(1)
		login(self.driver).clickdaoru3()
		sleep(1)
		login(self.driver).clickshang()
		sleep(1)
		os.system("C:\\Users\\Administrator\\MyScript\\excel\\sq.exe")
		sleep(2)
		login(self.driver).clicktijiao()
		sleep(3)
		self.assertEqual(login(self.driver).clickwanbi(),'导入完毕')
		sleep(1)
		login(self.driver).clickque()
		sleep(5)
		self.assertEqual(login(self.driver).dui(),'20')
		self.assertEqual(login(self.driver).cuo(),'0')
		#导入错误
		sleep(1)
		login(self.driver).clickshang2()
		sleep(1)
		os.system("C:\\Users\\Administrator\\MyScript\\excel\\se.exe")
		sleep(2)
		login(self.driver).clicktijiao()
		sleep(3)
		self.assertEqual(login(self.driver).clickwanbi(),'导入完毕')
		sleep(1)
		login(self.driver).clickque()
		sleep(5)
		self.assertEqual(login(self.driver).dui(),'10')
		self.assertEqual(login(self.driver).cuo(),'10')
		#导入大量
		sleep(1)
		login(self.driver).clickshang2()
		sleep(1)
		os.system("C:\\Users\\Administrator\\MyScript\\excel\\sw.exe")
		sleep(2)
		login(self.driver).clicktijiao()
		sleep(20)
		self.assertEqual(login(self.driver).clickwanbi(),'导入完毕')
		sleep(1)
		login(self.driver).clickque()
		sleep(5)
		self.assertEqual(login(self.driver).dui(),'983')
		self.assertEqual(login(self.driver).cuo(),'30')
		sleep(1)

	def tearDown(self):
		self.driver.quit()

if __name__ == '__main__':
	unittest.main()


